using Mithril.API.Abstractions.Commands.Interfaces;
using System.Security.Claims;

namespace Mithril.API.Abstractions.Commands.BaseClasses
{
    /// <summary>
    /// Command handler base class
    /// </summary>
    /// <typeparam name="TCommand">The type of the command.</typeparam>
    /// <seealso cref="ICommandHandler"/>
    public abstract class CommandHandlerBaseClass<TCommand, TViewModel> : ICommandHandler<TViewModel>
        where TCommand : class
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CommandHandlerBaseClass{TCommand}"/> class.
        /// </summary>
        protected CommandHandlerBaseClass()
        {
        }

        /// <summary>
        /// Gets the command type accepted.
        /// </summary>
        /// <value>The command type accepted.</value>
        public virtual string CommandName { get; } = typeof(TCommand).Name;

        /// <summary>
        /// Gets the tags (Used by OpenAPI, etc).
        /// </summary>
        /// <value>The tags (Used by OpenAPI, etc).</value>
        public virtual string[] Tags { get; } = Array.Empty<string>();

        /// <summary>
        /// Gets the type of the view model it accepts.
        /// </summary>
        /// <value>The type of the view model it accepts.</value>
        public Type ViewModelType { get; } = typeof(TViewModel);

        /// <summary>
        /// Creates the specified value.
        /// </summary>
        /// <param name="value">The value.</param>
        /// <param name="user">The user.</param>
        /// <returns>A command value converted from the view model.</returns>
        public abstract ICommand? Create(TViewModel? value, ClaimsPrincipal user);

        /// <summary>
        /// Handles the Command.
        /// </summary>
        /// <param name="arg">The argument.</param>
        /// <returns>Any events that are spawned by the command.</returns>
        public IEvent[] HandleCommand(params ICommand[] arg)
        {
            arg ??= Array.Empty<ICommand>();
            var Items = arg.Select(x => x as TCommand).Where(x => x is not null).ToArray();
            if (Items.Length == 0)
                return Array.Empty<IEvent>();
            return HandleCommand(Items) ?? Array.Empty<IEvent>();
        }

        /// <summary>
        /// Handles the command.
        /// </summary>
        /// <param name="args">The arguments.</param>
        /// <returns>The events generated by the command.</returns>
        protected abstract IEvent[] HandleCommand(params TCommand?[]? args);
    }
}