# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Test Pull Requests

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
  
    env:
      BUILD_CONFIG: 'Debug'
      SOLUTION: 'Mithril.Build.sln'

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '8.0.x' ]

    steps:
    - uses: actions/checkout@v5
    - name: Setup .NET SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v5.0.0
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Restore dependencies
      run: dotnet restore $SOLUTION
    - name: Build
      run: dotnet build $SOLUTION --no-restore --configuration $BUILD_CONFIG
    - name: Test
      run: dotnet test $SOLUTION /p:Configuration=$BUILD_CONFIG --no-build --verbosity normal --logger trx --results-directory "TestResults-${{ matrix.dotnet-version }}"
    - name: Upload test results
      uses: actions/upload-artifact@v5
      with:
        name: dotnet-results-${{ matrix.dotnet-version }}
        path: TestResults-${{ matrix.dotnet-version }}
      if: ${{ always() }}
